config:
  token: "xVNAJtViESEqgQn3AFyXjTbY"

nagroda:
  1-5:
    - "Item_1:10"
    - "Item_2:10"
    - "/give %player% stone"
  6-10:
    - "Item_1:20"
    - "Item_2:30"
    - "/give %player% dirt"
    - "message:Odeb"
  11:
    - "Item_1:99"
    - "Item_2:60"
    - "/give %player% diamond"
    - "message:&4&lgz"
  1+:
    - "message:&8Dostales nagrode"

items:
  Item_1:
    nazwa: "Nagroda"
    material: "DIAMOND"
    opis:
      - "test"
      - "rtest2"
  Item_2:
    nazwa: "Nagroda 2"
    material: "DIAMOND"
    opis:
      - "test"
      - "rtest2"