nagroda:
  token: "xVNAJtViESEqgQn3AFyXjTbY"
  1-5:
    - "Item_1:10"
    - "Item_2:10"
    - "/give %player% stone"
  6-10:
    - "Item_1:20"
    - "Item_2:30"
    - "/give %player% dirt"

items:
  Item_1:
    nazwa: "Nagroda"
    material: "DIAMOND"
    opis:
      - "test"
      - "rtest2"
  Item_2:
    nazwa: "Nagroda 2"
    material: "DIAMOND"
    opis:
      - "test"
      - "rtest2"