nagroda:
  item_1:
    wlaczone: true
    nazwa: "Nagroda"
    material: "DIAMOND"
    opis:
      - "test"
      - "rtest2"
  item_2:
    wlaczone: true
    nazwa: "Nagroda"
    material: "DIAMOND"
    opis:
      - "test"
      - "rtest2"
