nagroda:
  name: "Magiczny miecz"
  material: "DIAMOND_SWORD"
  lore:
    - "Potężny miecz rycerza"
    - "Został stworzony przez czarodzieja"
  enchantments:
    - "DAMAGE_ALL:5"
    - "FIRE_ASPECT:2"
    - "KNOCKBACK:2"
  flags:
    - "HIDE_ENCHANTS"
    - "HIDE_ATTRIBUTES"
  attributes:
    - name: "generic.attackDamage"
      amount: 10
      operation: "ADD_NUMBER"
      slot: "MAINHAND"